name: PR Test @horn/boris
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Compile & Test
        run: sbt test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}